# Generated by Django 5.2.1 on 2026-02-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator_app', '0002_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitool',
            name='category',
            field=models.CharField(blank=True, choices=[('nlp', 'NLP'), ('image', 'Image'), ('code', 'Code'), ('machine_learning', 'Machine Learning'), ('vision', 'Vision'), ('audio', 'Audio')], default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='aitool',
            name='documentation_link',
        ),
        migrations.RemoveField(
            model_name='aitool',
            name='tutorial_link',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='source',
        ),
        migrations.AddField(
            model_name='aitool',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aitool',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='link',
            field=models.URLField(help_text='Official website or product page.'),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='perplexity_query',
            field=models.CharField(blank=True, help_text='Optional custom AI query for this tool.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='rss_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
